department: anime-detection-bot
stack: backend
src_path: ../service
defaults:
  lambda_envs:
    LOG_LEVEL: DEBUG

envs:
  stable:
    lambda_envs:
      LOG_LEVEL: DEBUG

  prod:
    lambda_envs:
      LOG_LEVEL: DEBUG
