name: ci

on: push

jobs:
  build:
    environment: master
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Yandex Cloud Registry
        uses: docker/login-action@v2
        with:
          registry: cr.yandex
          username: ${{ secrets.YCR_USERNAME }}
          password: ${{ secrets.YCR_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./service/model_api/Dockerfile
          push: true
          tags: cr.yandex/${{ vars.YCR_ID }}/ml-image:latest
